# Generated by Django 3.0.4 on 2020-03-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20200315_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroi',
            old_name='name',
            new_name='nome',
        ),
    ]
